
-- ----------------------------
-- Table structure for CONFIG_TAGS_RELATION
-- ----------------------------
CREATE TABLE "SYSTEM"."CONFIG_TAGS_RELATION" (
  "ID" NUMBER(20,0) NOT NULL,
  "TAG_NAME" NVARCHAR2(128) NOT NULL,
  "TAG_TYPE" NVARCHAR2(64),
  "DATA_ID" NVARCHAR2(255) NOT NULL,
  "GROUP_ID" NVARCHAR2(128) NOT NULL,
  "TENANT_ID" NVARCHAR2(128),
  "NID" NUMBER(20,0) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SYSTEM"."CONFIG_TAGS_RELATION"."ID" IS 'id';
COMMENT ON COLUMN "SYSTEM"."CONFIG_TAGS_RELATION"."TAG_NAME" IS 'tag_name';
COMMENT ON COLUMN "SYSTEM"."CONFIG_TAGS_RELATION"."TAG_TYPE" IS 'tag_type';
COMMENT ON COLUMN "SYSTEM"."CONFIG_TAGS_RELATION"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "SYSTEM"."CONFIG_TAGS_RELATION"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "SYSTEM"."CONFIG_TAGS_RELATION"."TENANT_ID" IS 'tenant_id';
COMMENT ON TABLE "SYSTEM"."CONFIG_TAGS_RELATION" IS 'config_tag_relation';

-- ----------------------------
-- Records of CONFIG_TAGS_RELATION
-- ----------------------------
COMMIT;
COMMIT;

-- ----------------------------
-- Primary Key structure for table CONFIG_TAGS_RELATION
-- ----------------------------
ALTER TABLE "SYSTEM"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0012436" PRIMARY KEY ("NID");

-- ----------------------------
-- Checks structure for table CONFIG_TAGS_RELATION
-- ----------------------------
ALTER TABLE "SYSTEM"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0012388" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0012389" CHECK ("TAG_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0012390" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0012391" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0012392" CHECK ("NID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CONFIG_TAGS_RELATION
-- ----------------------------
CREATE INDEX "SYSTEM"."IDX_T"
  ON "SYSTEM"."CONFIG_TAGS_RELATION" ("TENANT_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
);
CREATE UNIQUE INDEX "SYSTEM"."UK_I_T_T"
  ON "SYSTEM"."CONFIG_TAGS_RELATION" ("ID" ASC, "TAG_NAME" ASC, "TAG_TYPE" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
);
