
-- ----------------------------
-- Table structure for CONFIG_INFO_BETA
-- ----------------------------
CREATE TABLE "SYSTEM"."CONFIG_INFO_BETA" (
  "ID" NUMBER(20,0) NOT NULL,
  "DATA_ID" NVARCHAR2(255) NOT NULL,
  "GROUP_ID" NVARCHAR2(128) NOT NULL,
  "APP_NAME" NVARCHAR2(128),
  "CONTENT" NCLOB NOT NULL,
  "BETA_IPS" NCLOB,
  "MD5" NVARCHAR2(32),
  "GMT_CREATE" DATE NOT NULL,
  "GMT_MODIFIED" DATE NOT NULL,
  "SRC_USER" NCLOB,
  "SRC_IP" NVARCHAR2(50),
  "TENANT_ID" NVARCHAR2(128),
  "ENCRYPTED_DATA_KEY" NCLOB NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_BETA"."ID" IS 'id';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_BETA"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_BETA"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_BETA"."APP_NAME" IS 'app_name';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_BETA"."CONTENT" IS 'content';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_BETA"."BETA_IPS" IS 'betaIps';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_BETA"."MD5" IS 'md5';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_BETA"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_BETA"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_BETA"."SRC_USER" IS 'source user';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_BETA"."SRC_IP" IS 'source ip';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_BETA"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_BETA"."ENCRYPTED_DATA_KEY" IS '秘钥';
COMMENT ON TABLE "SYSTEM"."CONFIG_INFO_BETA" IS 'config_info_beta';

-- ----------------------------
-- Records of CONFIG_INFO_BETA
-- ----------------------------
COMMIT;
COMMIT;

-- ----------------------------
-- Primary Key structure for table CONFIG_INFO_BETA
-- ----------------------------
ALTER TABLE "SYSTEM"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012433" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CONFIG_INFO_BETA
-- ----------------------------
ALTER TABLE "SYSTEM"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012363" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012364" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012365" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012366" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012367" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012368" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012369" CHECK ("ENCRYPTED_DATA_KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CONFIG_INFO_BETA
-- ----------------------------
CREATE UNIQUE INDEX "SYSTEM"."UK_D_G_T"
  ON "SYSTEM"."CONFIG_INFO_BETA" ("DATA_ID" ASC, "GROUP_ID" ASC, "TENANT_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
);
