
-- ----------------------------
-- Table structure for CONFIG_INFO_TAG
-- ----------------------------
CREATE TABLE "SYSTEM"."CONFIG_INFO_TAG" (
  "ID" NUMBER(20,0) NOT NULL,
  "DATA_ID" NVARCHAR2(255) NOT NULL,
  "GROUP_ID" NVARCHAR2(128) NOT NULL,
  "TENANT_ID" NVARCHAR2(128),
  "TAG_ID" NVARCHAR2(128) NOT NULL,
  "APP_NAME" NVARCHAR2(128),
  "CONTENT" NCLOB NOT NULL,
  "MD5" NVARCHAR2(32),
  "GMT_CREATE" DATE NOT NULL,
  "GMT_MODIFIED" DATE NOT NULL,
  "SRC_USER" NCLOB,
  "SRC_IP" NVARCHAR2(50)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_TAG"."ID" IS 'id';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_TAG"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_TAG"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_TAG"."TENANT_ID" IS 'tenant_id';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_TAG"."TAG_ID" IS 'tag_id';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_TAG"."APP_NAME" IS 'app_name';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_TAG"."CONTENT" IS 'content';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_TAG"."MD5" IS 'md5';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_TAG"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_TAG"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_TAG"."SRC_USER" IS 'source user';
COMMENT ON COLUMN "SYSTEM"."CONFIG_INFO_TAG"."SRC_IP" IS 'source ip';
COMMENT ON TABLE "SYSTEM"."CONFIG_INFO_TAG" IS 'config_info_tag';

-- ----------------------------
-- Records of CONFIG_INFO_TAG
-- ----------------------------
COMMIT;
COMMIT;

-- ----------------------------
-- Primary Key structure for table CONFIG_INFO_TAG
-- ----------------------------
ALTER TABLE "SYSTEM"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012435" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CONFIG_INFO_TAG
-- ----------------------------
ALTER TABLE "SYSTEM"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012381" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012382" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012383" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012384" CHECK ("TAG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012385" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012386" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012387" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CONFIG_INFO_TAG
-- ----------------------------
CREATE UNIQUE INDEX "SYSTEM"."UK_D_G_T_T"
  ON "SYSTEM"."CONFIG_INFO_TAG" ("DATA_ID" ASC, "GROUP_ID" ASC, "TENANT_ID" ASC, "TAG_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
);
