
-- ----------------------------
-- Table structure for GROUP_CAPACITY
-- ----------------------------
CREATE TABLE "SYSTEM"."GROUP_CAPACITY" (
  "ID" NUMBER(20,0) NOT NULL,
  "GROUP_ID" NVARCHAR2(128) NOT NULL,
  "QUOTA" NUMBER(11,0) NOT NULL,
  "USAGE" NUMBER(11,0) NOT NULL,
  "MAX_SIZE" NUMBER(11,0) NOT NULL,
  "MAX_AGGR_COUNT" NUMBER(11,0) NOT NULL,
  "MAX_AGGR_SIZE" NUMBER(11,0) NOT NULL,
  "MAX_HISTORY_COUNT" NUMBER(11,0) NOT NULL,
  "GMT_CREATE" DATE NOT NULL,
  "GMT_MODIFIED" DATE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SYSTEM"."GROUP_CAPACITY"."ID" IS '主键ID';
COMMENT ON COLUMN "SYSTEM"."GROUP_CAPACITY"."GROUP_ID" IS 'Group ID，空字符表示整个集群';
COMMENT ON COLUMN "SYSTEM"."GROUP_CAPACITY"."QUOTA" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "SYSTEM"."GROUP_CAPACITY"."USAGE" IS '使用量';
COMMENT ON COLUMN "SYSTEM"."GROUP_CAPACITY"."MAX_SIZE" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "SYSTEM"."GROUP_CAPACITY"."MAX_AGGR_COUNT" IS '聚合子配置最大个数，，0表示使用默认值';
COMMENT ON COLUMN "SYSTEM"."GROUP_CAPACITY"."MAX_AGGR_SIZE" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "SYSTEM"."GROUP_CAPACITY"."MAX_HISTORY_COUNT" IS '最大变更历史数量';
COMMENT ON COLUMN "SYSTEM"."GROUP_CAPACITY"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "SYSTEM"."GROUP_CAPACITY"."GMT_MODIFIED" IS '修改时间';
COMMENT ON TABLE "SYSTEM"."GROUP_CAPACITY" IS '集群、各Group容量信息表';

-- ----------------------------
-- Records of GROUP_CAPACITY
-- ----------------------------
COMMIT;
COMMIT;

-- ----------------------------
-- Primary Key structure for table GROUP_CAPACITY
-- ----------------------------
ALTER TABLE "SYSTEM"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012438" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table GROUP_CAPACITY
-- ----------------------------
ALTER TABLE "SYSTEM"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012393" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012394" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012395" CHECK ("QUOTA" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012396" CHECK ("USAGE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012397" CHECK ("MAX_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012398" CHECK ("MAX_AGGR_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012399" CHECK ("MAX_AGGR_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012400" CHECK ("MAX_HISTORY_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012401" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012402" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table GROUP_CAPACITY
-- ----------------------------
CREATE UNIQUE INDEX "SYSTEM"."UK_GR_ID"
  ON "SYSTEM"."GROUP_CAPACITY" ("GROUP_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
);
