CREATE sequence SEQ_ID START WITH 10 INCREMENT BY 1 nomaxvalue nocycle nocache;

DROP TABLE "CONFIG_INFO";
CREATE TABLE "CONFIG_INFO" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "DATA_ID" NVARCHAR2(255) VISIBLE NOT NULL,
  "GROUP_ID" NVARCHAR2(255) VISIBLE,
  "CONTENT" NCLOB VISIBLE NOT NULL,
  "MD5" NVARCHAR2(32) VISIBLE,
  "GMT_CREATE" DATE VISIBLE NOT NULL,
  "GMT_MODIFIED" DATE VISIBLE NOT NULL,
  "SRC_USER" NCLOB VISIBLE,
  "SRC_IP" NVARCHAR2(50) VISIBLE,
  "APP_NAME" NVARCHAR2(128) VISIBLE,
  "TENANT_ID" NVARCHAR2(128) VISIBLE DEFAULT '',
  "C_DESC" NVARCHAR2(256) VISIBLE,
  "C_USE" NVARCHAR2(64) VISIBLE,
  "EFFECT" NVARCHAR2(64) VISIBLE,
  "TYPE" NVARCHAR2(64) VISIBLE,
  "C_SCHEMA" NCLOB VISIBLE,
  "ENCRYPTED_DATA_KEY" NCLOB VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CONFIG_INFO"."ID" IS 'id';
COMMENT ON COLUMN "CONFIG_INFO"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "CONFIG_INFO"."CONTENT" IS 'content';
COMMENT ON COLUMN "CONFIG_INFO"."MD5" IS 'md5';
COMMENT ON COLUMN "CONFIG_INFO"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "CONFIG_INFO"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "CONFIG_INFO"."SRC_USER" IS 'source user';
COMMENT ON COLUMN "CONFIG_INFO"."SRC_IP" IS 'source ip';
COMMENT ON COLUMN "CONFIG_INFO"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "CONFIG_INFO"."ENCRYPTED_DATA_KEY" IS '秘钥';
COMMENT ON TABLE "CONFIG_INFO" IS 'config_info';

-- ----------------------------
-- Records of CONFIG_INFO
-- ----------------------------
COMMIT;
COMMIT;

-- ----------------------------
-- Table structure for CONFIG_INFO_AGGR
-- ----------------------------
DROP TABLE "CONFIG_INFO_AGGR";
CREATE TABLE "CONFIG_INFO_AGGR" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "DATA_ID" NVARCHAR2(255) VISIBLE NOT NULL,
  "GROUP_ID" NVARCHAR2(255) VISIBLE NOT NULL,
  "DATUM_ID" NVARCHAR2(255) VISIBLE NOT NULL,
  "CONTENT" NCLOB VISIBLE NOT NULL,
  "GMT_MODIFIED" DATE VISIBLE NOT NULL,
  "APP_NAME" NVARCHAR2(128) VISIBLE,
  "TENANT_ID" NVARCHAR2(128) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."ID" IS 'id';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."DATUM_ID" IS 'datum_id';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."CONTENT" IS '内容';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."TENANT_ID" IS '租户字段';
COMMENT ON TABLE "CONFIG_INFO_AGGR" IS '增加租户字段';

-- ----------------------------
-- Records of CONFIG_INFO_AGGR
-- ----------------------------
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('121', '3nL', 'zp5', 'iUA', 'You cannot save                    ', TO_DATE('2019-07-22 05:48:28', 'SYYYY-MM-DD HH24:MI:SS'), 'Nishimura Hikaru', 'VaQ');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('122', '7cA', 'daa', 'FEn', 'It collects process                ', TO_DATE('2008-06-10 17:28:11', 'SYYYY-MM-DD HH24:MI:SS'), 'Okamoto Seiko', '47Y');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('123', 'TEn', '8iN', 'ZIx', 'How we spend our                   ', TO_DATE('2004-01-15 11:59:22', 'SYYYY-MM-DD HH24:MI:SS'), 'Kathleen Wright', 'zea');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('124', 'GPz', 'lVW', '5Cj', 'The repository database            ', TO_DATE('2016-01-11 06:00:25', 'SYYYY-MM-DD HH24:MI:SS'), 'Meng Anqi', 'JWJ');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('125', 'cc4', 'FlS', 'eYP', 'It is used while                   ', TO_DATE('2002-01-10 18:12:58', 'SYYYY-MM-DD HH24:MI:SS'), 'Chen Zhennan', 'am6');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('126', '6Eq', 'bno', 'G3A', 'You must be the                    ', TO_DATE('2020-10-22 11:34:09', 'SYYYY-MM-DD HH24:MI:SS'), 'Hasegawa Hikaru', 'oVF');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('127', 'n4g', 'O4H', 'Mjm', 'How we spend our                   ', TO_DATE('2008-11-24 10:07:06', 'SYYYY-MM-DD HH24:MI:SS'), 'Sakai Kasumi', 'x9x');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('128', 'CXO', 'cSa', '3Di', 'A man’s best friends             ', TO_DATE('2005-12-03 21:32:41', 'SYYYY-MM-DD HH24:MI:SS'), 'Gong Lan', '0aV');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('129', 'HPL', 'TO9', 'P1n', 'Typically, it is                   ', TO_DATE('2012-01-03 12:49:51', 'SYYYY-MM-DD HH24:MI:SS'), 'Takagi Hana', 'Azx');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('130', 'U9H', 'i3Z', 'h8l', 'If your Internet                   ', TO_DATE('2007-08-30 09:24:52', 'SYYYY-MM-DD HH24:MI:SS'), 'Linda Kennedy', 'fMK');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('131', '5nu', 'vDR', 'UGZ', 'Navicat is a multi-connections     ', TO_DATE('2001-04-11 03:31:12', 'SYYYY-MM-DD HH24:MI:SS'), 'Kevin Crawford', 'p9H');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('132', 'bWW', 'wKW', 'uxn', 'I will greet this                  ', TO_DATE('2009-01-01 08:35:39', 'SYYYY-MM-DD HH24:MI:SS'), 'Yam Sze Yu', 'rcz');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('133', 'dCx', 'ed7', 'Wk1', 'Navicat Monitor                    ', TO_DATE('2015-09-10 02:26:34', 'SYYYY-MM-DD HH24:MI:SS'), 'Murata Eita', '4xe');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('134', 'M4o', 'KrW', 'kxW', 'If it scares you,                  ', TO_DATE('2000-04-01 23:34:52', 'SYYYY-MM-DD HH24:MI:SS'), 'Yamaguchi Tsubasa', 'pXM');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('135', 'Cjc', 'JIF', 'LL6', 'After comparing                    ', TO_DATE('2000-09-18 13:39:29', 'SYYYY-MM-DD HH24:MI:SS'), 'Craig Richardson', 'Xga');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('136', 'src', 'cSE', 'aEO', 'After comparing                    ', TO_DATE('2011-10-31 05:19:42', 'SYYYY-MM-DD HH24:MI:SS'), 'Hsuan Tak Wah', 'YJN');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('137', 'PYh', '1sS', 'iXO', 'Export Wizard allows               ', TO_DATE('2009-09-07 10:35:42', 'SYYYY-MM-DD HH24:MI:SS'), 'Tang Yunxi', '95T');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('138', '6Av', 'Csw', 'nFZ', 'Monitored servers                  ', TO_DATE('2001-05-23 02:00:30', 'SYYYY-MM-DD HH24:MI:SS'), 'Du Anqi', 'm21');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('139', 'Tml', 'bt3', '2RM', 'There is no way                    ', TO_DATE('2017-08-08 13:08:57', 'SYYYY-MM-DD HH24:MI:SS'), 'Barry Wells', 'wV2');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('140', 'mHl', 'Too', 'iQt', 'In the middle of                   ', TO_DATE('2019-05-29 01:28:48', 'SYYYY-MM-DD HH24:MI:SS'), 'Kam Wai Man', '52h');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('141', 'Nnx', 'IEa', 'ehZ', 'To clear or reload                 ', TO_DATE('2010-05-12 21:14:25', 'SYYYY-MM-DD HH24:MI:SS'), 'Yeung Lik Sun', '8Ed');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('142', '1d0', 'cPn', 'mi5', 'I destroy my enemies               ', TO_DATE('2015-12-19 19:31:30', 'SYYYY-MM-DD HH24:MI:SS'), 'Hayashi Rin', 'f1d');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('143', 'eUl', 'rAY', 'SV0', 'You can select any                 ', TO_DATE('2000-07-13 06:07:59', 'SYYYY-MM-DD HH24:MI:SS'), 'Hayashi Eita', 'I46');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('144', '1oe', 'WuT', '7o3', 'How we spend our                   ', TO_DATE('2010-04-16 08:13:34', 'SYYYY-MM-DD HH24:MI:SS'), 'Dai Wai Lam', 'yfh');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('145', 'm5k', '3iw', '3h2', 'After comparing                    ', TO_DATE('2021-01-23 15:18:58', 'SYYYY-MM-DD HH24:MI:SS'), 'Aaron Torres', 'viz');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('146', 'DUK', 'org', 'b9Y', 'I destroy my enemies               ', TO_DATE('2013-10-04 13:01:18', 'SYYYY-MM-DD HH24:MI:SS'), 'Ku Tin Wing', 'Pjc');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('147', 'owo', 'Zwk', 'jc5', 'A comfort zone is                  ', TO_DATE('2005-01-30 15:59:27', 'SYYYY-MM-DD HH24:MI:SS'), 'Irene Shaw', 'xsJ');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('148', 'zJX', '4mn', 'Urv', 'Import Wizard allows               ', TO_DATE('2013-08-16 03:28:15', 'SYYYY-MM-DD HH24:MI:SS'), 'So Ling Ling', 'KGA');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('149', 'W4C', 'fRQ', 'G6Q', 'If opportunity doesn’t           ', TO_DATE('2019-11-30 08:11:42', 'SYYYY-MM-DD HH24:MI:SS'), 'Mike Ruiz', 'Lqu');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('1', '0x95FJST11', 'tQB1IB0RKp', 'VEwGFTnEve', 'Navicat Cloud could not connect and access your databases. By which it means, it could only store your connection settings, queries, model files, and virtual group; your database passwords and data (e.g. tables, views, etc) will not be stored to Navicat Cloud. HTTP Tunneling is a method for connecting to a server that uses the same protocol (http://) and the same port (port 80) as a web server does. I will greet this day with love in my heart. Navicat Monitor can be installed on any local computer or virtual machine and does not require any software installation on the servers being monitored. Import Wizard allows you to import data to tables/collections from CSV, TXT, XML, DBF and more. A man’s best friends are his ten fingers. The Main Window consists of several toolbars and panes for you to work on connections, database objects and advanced tools. To start working with your server in Navicat, you should first establish a connection or several connections using the Connection window. You must be the change you wish to see in the world. It can also manage cloud databases such as Amazon Redshift, Amazon RDS, Alibaba Cloud. Features in Navicat are sophisticated enough to provide professional developers for all their specific needs, yet easy to learn for users who are new to database server. There is no way to happiness. Happiness is the way. SQL Editor allows you to create and edit SQL text, prepare and execute selected queries. In other words, Navicat provides the ability for data in different databases and/or schemas to be kept up-to-date so that each repository contains the same information.', TO_DATE('2019-01-01 19:47:20', 'SYYYY-MM-DD HH24:MI:SS'), 'Yamashita Ayano', '9NWVTmRZVx');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('2', '5JzaGYQssD', 'BwCRpjm6X4', 'mcRw8gnWZZ', 'To connect to a database or schema, simply double-click it in the pane. The first step is as good as half over. Such sessions are also susceptible to session hijacking, where a malicious user takes over your session once you have authenticated. Navicat is a multi-connections Database Administration tool allowing you to connect to MySQL, Oracle, PostgreSQL, SQLite, SQL Server, MariaDB and/or MongoDB databases, making database administration to multiple kinds of database so easy. To start working with your server in Navicat, you should first establish a connection or several connections using the Connection window. Flexible settings enable you to set up a custom key for comparison and synchronization. To connect to a database or schema, simply double-click it in the pane. Actually it is just in an idea when feel oneself can achieve and cannot achieve. Navicat provides a wide range advanced features, such as compelling code editing capabilities, smart code-completion, SQL formatting, and more. Success consists of going from failure to failure without loss of enthusiasm. Secure Sockets Layer(SSL) is a protocol for transmitting private documents via the Internet. Navicat Monitor requires a repository to store alerts and metrics for historical analysis. Genius is an infinite capacity for taking pains. I destroy my enemies when I make them my friends. If the Show objects under schema in navigation pane option is checked at the Preferences window, all database objects are also displayed in the pane. It wasn’t raining when Noah built the ark. It can also manage cloud databases such as Amazon Redshift, Amazon RDS, Alibaba Cloud. Features in Navicat are sophisticated enough to provide professional developers for all their specific needs, yet easy to learn for users who are new to database server. Navicat provides a wide range advanced features, such as compelling code editing capabilities, smart code-completion, SQL formatting, and more. HTTP Tunneling is a method for connecting to a server that uses the same protocol (http://) and the same port (port 80) as a web server does. A query is used to extract data from the database in a readable format according to the user''s request. HTTP Tunneling is a method for connecting to a server that uses the same protocol (http://) and the same port (port 80) as a web server does. If the Show objects under schema in navigation pane option is checked at the Preferences window, all database objects are also displayed in the pane.', TO_DATE('2001-12-17 06:31:45', 'SYYYY-MM-DD HH24:MI:SS'), 'Fong On Kay', 'bJj2zHIk6d');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('100', '0x9', '5FJ', 'ST1', 'If the plan doesn’t              ', TO_DATE('2000-11-30 15:15:23', 'SYYYY-MM-DD HH24:MI:SS'), 'Yamashita Ayano', '0RK');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('101', 'FTn', 'Eve', 'LfE', 'I will greet this                  ', TO_DATE('2015-03-18 14:31:20', 'SYYYY-MM-DD HH24:MI:SS'), 'Donald Washington', '0FJ');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('102', 'xc2', '8o8', '9NW', 'SSH serves to prevent              ', TO_DATE('2007-11-25 12:26:11', 'SYYYY-MM-DD HH24:MI:SS'), 'Kondo Sakura', 'VxT');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('103', '5Jz', 'aGY', 'Qss', 'You can select any                 ', TO_DATE('2020-07-23 13:32:35', 'SYYYY-MM-DD HH24:MI:SS'), 'Xie Lu', 'jm6');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('104', 'mcR', 'w8g', 'nWZ', 'The first step is                  ', TO_DATE('2018-06-02 07:11:24', 'SYYYY-MM-DD HH24:MI:SS'), 'Lo Tak Wah', '1Fk');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('105', 'fwr', 'Z1M', 'jtt', 'If the Show objects                ', TO_DATE('2010-07-05 20:27:58', 'SYYYY-MM-DD HH24:MI:SS'), 'Choi Ka Ming', '2Zi');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('106', 'UX5', 'RRM', '5Hb', 'The past has no                    ', TO_DATE('2013-09-18 03:04:49', 'SYYYY-MM-DD HH24:MI:SS'), 'Yung Lai Yan', 'Ik6');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('107', 'lO8', '8Da', 'QHE', 'If the plan doesn’t              ', TO_DATE('2006-03-01 01:15:31', 'SYYYY-MM-DD HH24:MI:SS'), 'Mildred Silva', 'naY');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('108', 'rKF', 'TOO', 'RbY', 'What you get by                    ', TO_DATE('2002-04-23 08:35:48', 'SYYYY-MM-DD HH24:MI:SS'), 'Lo Tak Wah', 'ygf');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('109', 'YwM', '38A', 'D2I', 'Navicat Monitor                    ', TO_DATE('2015-05-15 02:11:20', 'SYYYY-MM-DD HH24:MI:SS'), 'Yuen Chung Yin', 'lIb');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('110', '92v', 'i9u', '32n', 'Navicat provides                   ', TO_DATE('2012-03-03 14:52:23', 'SYYYY-MM-DD HH24:MI:SS'), 'Kudo Sara', 'oJP');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('111', 'nKN', 'f2L', 'rTq', 'There is no way                    ', TO_DATE('2017-11-07 01:08:38', 'SYYYY-MM-DD HH24:MI:SS'), 'Ogawa Mio', 'am6');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('112', 'tMJ', '04w', 'yvi', 'Sometimes you win,                 ', TO_DATE('2010-01-10 22:13:31', 'SYYYY-MM-DD HH24:MI:SS'), 'Su Jialun', 'MXu');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('113', 'seS', 'PI3', 'GBv', 'Optimism is the                    ', TO_DATE('2007-01-16 11:42:13', 'SYYYY-MM-DD HH24:MI:SS'), 'Jiang Jiehong', 'pAb');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('114', 'P6H', 'xD2', 'AoX', 'Remember that failure              ', TO_DATE('2018-03-24 15:23:30', 'SYYYY-MM-DD HH24:MI:SS'), 'Chang Chi Ming', 'Mug');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('115', 'h3n', 'IH7', 'UFI', 'Instead of wondering               ', TO_DATE('2005-04-10 10:32:01', 'SYYYY-MM-DD HH24:MI:SS'), 'Rhonda Mitchell', 'iui');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('116', 'SKw', 'Ffe', '3gQ', 'Navicat authorizes                 ', TO_DATE('2019-05-11 12:05:54', 'SYYYY-MM-DD HH24:MI:SS'), 'Lu Yunxi', 'LbU');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('117', 'Fjw', 'KR5', 'v1e', 'Anyone who has never               ', TO_DATE('2015-08-06 06:38:43', 'SYYYY-MM-DD HH24:MI:SS'), 'Charles Castro', 'qkG');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('118', 'gfz', 'pWA', 'wI7', 'I destroy my enemies               ', TO_DATE('2018-06-18 18:27:47', 'SYYYY-MM-DD HH24:MI:SS'), 'Loui Wing Sze', 'Idu');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('119', 'Pnq', 'RMu', '1Mq', 'Sometimes you win,                 ', TO_DATE('2016-01-13 09:29:32', 'SYYYY-MM-DD HH24:MI:SS'), 'Yao Lu', '6aC');
INSERT INTO "CONFIG_INFO_AGGR" VALUES ('120', 'q95', 'QRh', 'd3n', 'The repository database            ', TO_DATE('2007-06-24 15:46:37', 'SYYYY-MM-DD HH24:MI:SS'), 'Tsui Chun Yu', 'I4W');
COMMIT;
COMMIT;

-- ----------------------------
-- Table structure for CONFIG_INFO_BETA
-- ----------------------------
DROP TABLE "CONFIG_INFO_BETA";
CREATE TABLE "CONFIG_INFO_BETA" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "DATA_ID" NVARCHAR2(255) VISIBLE NOT NULL,
  "GROUP_ID" NVARCHAR2(128) VISIBLE NOT NULL,
  "APP_NAME" NVARCHAR2(128) VISIBLE,
  "CONTENT" NCLOB VISIBLE NOT NULL,
  "BETA_IPS" NCLOB VISIBLE,
  "MD5" NVARCHAR2(32) VISIBLE,
  "GMT_CREATE" DATE VISIBLE NOT NULL,
  "GMT_MODIFIED" DATE VISIBLE NOT NULL,
  "SRC_USER" NCLOB VISIBLE,
  "SRC_IP" NVARCHAR2(50) VISIBLE,
  "TENANT_ID" NVARCHAR2(128) VISIBLE,
  "ENCRYPTED_DATA_KEY" NCLOB VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CONFIG_INFO_BETA"."ID" IS 'id';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."APP_NAME" IS 'app_name';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."CONTENT" IS 'content';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."BETA_IPS" IS 'betaIps';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."MD5" IS 'md5';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."SRC_USER" IS 'source user';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."SRC_IP" IS 'source ip';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."ENCRYPTED_DATA_KEY" IS '秘钥';
COMMENT ON TABLE "CONFIG_INFO_BETA" IS 'config_info_beta';

-- ----------------------------
-- Records of CONFIG_INFO_BETA
-- ----------------------------
COMMIT;
COMMIT;

-- ----------------------------
-- Table structure for CONFIG_INFO_TAG
-- ----------------------------
DROP TABLE "CONFIG_INFO_TAG";
CREATE TABLE "CONFIG_INFO_TAG" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "DATA_ID" NVARCHAR2(255) VISIBLE NOT NULL,
  "GROUP_ID" NVARCHAR2(128) VISIBLE NOT NULL,
  "TENANT_ID" NVARCHAR2(128) VISIBLE,
  "TAG_ID" NVARCHAR2(128) VISIBLE NOT NULL,
  "APP_NAME" NVARCHAR2(128) VISIBLE,
  "CONTENT" NCLOB VISIBLE NOT NULL,
  "MD5" NVARCHAR2(32) VISIBLE,
  "GMT_CREATE" DATE VISIBLE NOT NULL,
  "GMT_MODIFIED" DATE VISIBLE NOT NULL,
  "SRC_USER" NCLOB VISIBLE,
  "SRC_IP" NVARCHAR2(50) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CONFIG_INFO_TAG"."ID" IS 'id';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."TENANT_ID" IS 'tenant_id';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."TAG_ID" IS 'tag_id';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."APP_NAME" IS 'app_name';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."CONTENT" IS 'content';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."MD5" IS 'md5';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."SRC_USER" IS 'source user';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."SRC_IP" IS 'source ip';
COMMENT ON TABLE "CONFIG_INFO_TAG" IS 'config_info_tag';

-- ----------------------------
-- Records of CONFIG_INFO_TAG
-- ----------------------------
COMMIT;
COMMIT;

-- ----------------------------
-- Table structure for CONFIG_TAGS_RELATION
-- ----------------------------
DROP TABLE "CONFIG_TAGS_RELATION";
CREATE TABLE "CONFIG_TAGS_RELATION" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "TAG_NAME" NVARCHAR2(128) VISIBLE NOT NULL,
  "TAG_TYPE" NVARCHAR2(64) VISIBLE,
  "DATA_ID" NVARCHAR2(255) VISIBLE NOT NULL,
  "GROUP_ID" NVARCHAR2(128) VISIBLE NOT NULL,
  "TENANT_ID" NVARCHAR2(128) VISIBLE,
  "NID" NUMBER(20,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."ID" IS 'id';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."TAG_NAME" IS 'tag_name';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."TAG_TYPE" IS 'tag_type';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."TENANT_ID" IS 'tenant_id';
COMMENT ON TABLE "CONFIG_TAGS_RELATION" IS 'config_tag_relation';

-- ----------------------------
-- Records of CONFIG_TAGS_RELATION
-- ----------------------------
COMMIT;
COMMIT;

-- ----------------------------
-- Table structure for GROUP_CAPACITY
-- ----------------------------
DROP TABLE "GROUP_CAPACITY";
CREATE TABLE "GROUP_CAPACITY" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "GROUP_ID" NVARCHAR2(128) VISIBLE NOT NULL,
  "QUOTA" NUMBER(11,0) VISIBLE NOT NULL,
  "USAGE" NUMBER(11,0) VISIBLE NOT NULL,
  "MAX_SIZE" NUMBER(11,0) VISIBLE NOT NULL,
  "MAX_AGGR_COUNT" NUMBER(11,0) VISIBLE NOT NULL,
  "MAX_AGGR_SIZE" NUMBER(11,0) VISIBLE NOT NULL,
  "MAX_HISTORY_COUNT" NUMBER(11,0) VISIBLE NOT NULL,
  "GMT_CREATE" DATE VISIBLE NOT NULL,
  "GMT_MODIFIED" DATE VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "GROUP_CAPACITY"."ID" IS '主键ID';
COMMENT ON COLUMN "GROUP_CAPACITY"."GROUP_ID" IS 'Group ID，空字符表示整个集群';
COMMENT ON COLUMN "GROUP_CAPACITY"."QUOTA" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "GROUP_CAPACITY"."USAGE" IS '使用量';
COMMENT ON COLUMN "GROUP_CAPACITY"."MAX_SIZE" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "GROUP_CAPACITY"."MAX_AGGR_COUNT" IS '聚合子配置最大个数，，0表示使用默认值';
COMMENT ON COLUMN "GROUP_CAPACITY"."MAX_AGGR_SIZE" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "GROUP_CAPACITY"."MAX_HISTORY_COUNT" IS '最大变更历史数量';
COMMENT ON COLUMN "GROUP_CAPACITY"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "GROUP_CAPACITY"."GMT_MODIFIED" IS '修改时间';
COMMENT ON TABLE "GROUP_CAPACITY" IS '集群、各Group容量信息表';

-- ----------------------------
-- Records of GROUP_CAPACITY
-- ----------------------------
COMMIT;
COMMIT;

-- ----------------------------
-- Table structure for HIS_CONFIG_INFO
-- ----------------------------
DROP TABLE "HIS_CONFIG_INFO";
CREATE TABLE "HIS_CONFIG_INFO" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "NID" NUMBER(20,0) VISIBLE NOT NULL,
  "DATA_ID" NVARCHAR2(255) VISIBLE NOT NULL,
  "GROUP_ID" NVARCHAR2(128) VISIBLE NOT NULL,
  "APP_NAME" NVARCHAR2(128) VISIBLE,
  "CONTENT" NCLOB VISIBLE NOT NULL,
  "MD5" NVARCHAR2(32) VISIBLE,
  "GMT_CREATE" DATE VISIBLE NOT NULL,
  "GMT_MODIFIED" DATE VISIBLE NOT NULL,
  "SRC_USER" NCLOB VISIBLE,
  "SRC_IP" NVARCHAR2(50) VISIBLE,
  "OP_TYPE" NCHAR(10) VISIBLE,
  "TENANT_ID" NVARCHAR2(128) VISIBLE,
  "ENCRYPTED_DATA_KEY" NCLOB VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "HIS_CONFIG_INFO"."APP_NAME" IS 'app_name';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."ENCRYPTED_DATA_KEY" IS '秘钥';
COMMENT ON TABLE "HIS_CONFIG_INFO" IS '多租户改造';

-- ----------------------------
-- Records of HIS_CONFIG_INFO
-- ----------------------------
COMMIT;
COMMIT;

-- ----------------------------
-- Table structure for PERMISSIONS
-- ----------------------------
DROP TABLE "PERMISSIONS";
CREATE TABLE "PERMISSIONS" (
  "ROLE" NVARCHAR2(50) VISIBLE NOT NULL,
  "RESOURCE" NVARCHAR2(255) VISIBLE NOT NULL,
  "ACTION" NVARCHAR2(8) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PERMISSIONS
-- ----------------------------
INSERT INTO "PERMISSIONS" VALUES ('user', ':*:*', 'rw');
COMMIT;
COMMIT;

-- ----------------------------
-- Table structure for ROLES
-- ----------------------------
DROP TABLE "ROLES";
CREATE TABLE "ROLES" (
  "USERNAME" NVARCHAR2(50) VISIBLE NOT NULL,
  "ROLE" NVARCHAR2(50) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of ROLES
-- ----------------------------
INSERT INTO "ROLES" VALUES ('fxz', 'user');
INSERT INTO "ROLES" VALUES ('nacos', 'ROLE_ADMIN');
COMMIT;
COMMIT;

-- ----------------------------
-- Table structure for TENANT_CAPACITY
-- ----------------------------
DROP TABLE "TENANT_CAPACITY";
CREATE TABLE "TENANT_CAPACITY" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "TENANT_ID" NVARCHAR2(128) VISIBLE NOT NULL,
  "QUOTA" NUMBER(11,0) VISIBLE NOT NULL,
  "USAGE" NUMBER(11,0) VISIBLE NOT NULL,
  "MAX_SIZE" NUMBER(11,0) VISIBLE NOT NULL,
  "MAX_AGGR_COUNT" NUMBER(11,0) VISIBLE NOT NULL,
  "MAX_AGGR_SIZE" NUMBER(11,0) VISIBLE NOT NULL,
  "MAX_HISTORY_COUNT" NUMBER(11,0) VISIBLE NOT NULL,
  "GMT_CREATE" DATE VISIBLE NOT NULL,
  "GMT_MODIFIED" DATE VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "TENANT_CAPACITY"."ID" IS '主键ID';
COMMENT ON COLUMN "TENANT_CAPACITY"."TENANT_ID" IS 'Tenant ID';
COMMENT ON COLUMN "TENANT_CAPACITY"."QUOTA" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "TENANT_CAPACITY"."USAGE" IS '使用量';
COMMENT ON COLUMN "TENANT_CAPACITY"."MAX_SIZE" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "TENANT_CAPACITY"."MAX_AGGR_COUNT" IS '聚合子配置最大个数';
COMMENT ON COLUMN "TENANT_CAPACITY"."MAX_AGGR_SIZE" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "TENANT_CAPACITY"."MAX_HISTORY_COUNT" IS '最大变更历史数量';
COMMENT ON COLUMN "TENANT_CAPACITY"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "TENANT_CAPACITY"."GMT_MODIFIED" IS '修改时间';
COMMENT ON TABLE "TENANT_CAPACITY" IS '租户容量信息表';

-- ----------------------------
-- Records of TENANT_CAPACITY
-- ----------------------------
COMMIT;
COMMIT;

-- ----------------------------
-- Table structure for TENANT_INFO
-- ----------------------------
DROP TABLE "TENANT_INFO";
CREATE TABLE "TENANT_INFO" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "KP" NVARCHAR2(128) VISIBLE NOT NULL,
  "TENANT_ID" NVARCHAR2(128) VISIBLE,
  "TENANT_NAME" NVARCHAR2(128) VISIBLE,
  "TENANT_DESC" NVARCHAR2(256) VISIBLE,
  "CREATE_SOURCE" NVARCHAR2(32) VISIBLE,
  "GMT_CREATE" NUMBER(20,0) VISIBLE NOT NULL,
  "GMT_MODIFIED" NUMBER(20,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "TENANT_INFO"."ID" IS 'id';
COMMENT ON COLUMN "TENANT_INFO"."KP" IS 'kp';
COMMENT ON COLUMN "TENANT_INFO"."TENANT_ID" IS 'tenant_id';
COMMENT ON COLUMN "TENANT_INFO"."TENANT_NAME" IS 'tenant_name';
COMMENT ON COLUMN "TENANT_INFO"."TENANT_DESC" IS 'tenant_desc';
COMMENT ON COLUMN "TENANT_INFO"."CREATE_SOURCE" IS 'create_source';
COMMENT ON COLUMN "TENANT_INFO"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "TENANT_INFO"."GMT_MODIFIED" IS '修改时间';
COMMENT ON TABLE "TENANT_INFO" IS 'tenant_info';

-- ----------------------------
-- Records of TENANT_INFO
-- ----------------------------
INSERT INTO "TENANT_INFO" VALUES ('123', '1', '354b449d-411e-494d-9e2d-cee74197fd76', 'zxcxzc', 'zxczxc', 'nacos', '1672036949003', '1672036949003');
COMMIT;
COMMIT;

-- ----------------------------
-- Table structure for USERS
-- ----------------------------
DROP TABLE "USERS";
CREATE TABLE "USERS" (
  "USERNAME" NVARCHAR2(50) VISIBLE NOT NULL,
  "PASSWORD" NVARCHAR2(500) VISIBLE NOT NULL,
  "ENABLED" NUMBER(4,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of USERS
-- ----------------------------
INSERT INTO "USERS" VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', '1');
INSERT INTO "USERS" VALUES ('fxz', '$2a$10$kgxkmVzxCrvy43WNQ57Gk.b5eaJ9SwGZ1DxXUeWAlGjh3Htvi/nGC', '1');
COMMIT;
COMMIT;

-- ----------------------------
-- Sequence structure for SEQ_ID
-- ----------------------------
DROP SEQUENCE "SEQ_ID";
CREATE SEQUENCE "SEQ_ID" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Primary Key structure for table CONFIG_INFO
-- ----------------------------
ALTER TABLE "CONFIG_INFO" ADD CONSTRAINT "SYS_C0012437" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CONFIG_INFO
-- ----------------------------
ALTER TABLE "CONFIG_INFO" ADD CONSTRAINT "SYS_C0012370" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO" ADD CONSTRAINT "SYS_C0012371" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO" ADD CONSTRAINT "SYS_C0012372" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO" ADD CONSTRAINT "SYS_C0012373" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO" ADD CONSTRAINT "SYS_C0012374" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO" ADD CONSTRAINT "SYS_C007917" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO" ADD CONSTRAINT "SYS_C007918" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO" ADD CONSTRAINT "SYS_C007919" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO" ADD CONSTRAINT "SYS_C007920" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO" ADD CONSTRAINT "SYS_C007921" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CONFIG_INFO
-- ----------------------------
CREATE UNIQUE INDEX "U_G_T"
  ON "CONFIG_INFO" ("DATA_ID" ASC, "GROUP_ID" ASC, "TENANT_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Triggers structure for table CONFIG_INFO
-- ----------------------------
CREATE TRIGGER "TG_CONFIG_INFO" BEFORE INSERT ON "CONFIG_INFO" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
begin
select /*序列*/SEQ_ID.nextval into:new.ID/*主键*/ from dual;
end;
/

-- ----------------------------
-- Primary Key structure for table CONFIG_INFO_AGGR
-- ----------------------------
ALTER TABLE "CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0012434" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CONFIG_INFO_AGGR
-- ----------------------------
ALTER TABLE "CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0012375" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0012376" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0012377" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0012378" CHECK ("DATUM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0012379" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C0012380" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C007874" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C007875" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C007876" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C007877" CHECK ("DATUM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C007878" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_AGGR" ADD CONSTRAINT "SYS_C007879" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CONFIG_INFO_AGGR
-- ----------------------------
CREATE UNIQUE INDEX "UK_DI_GR_T_D"
  ON "CONFIG_INFO_AGGR" ("DATA_ID" ASC, "GROUP_ID" ASC, "TENANT_ID" ASC, "DATUM_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table CONFIG_INFO_BETA
-- ----------------------------
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012433" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CONFIG_INFO_BETA
-- ----------------------------
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012363" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012364" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012365" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012366" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012367" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012368" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C0012369" CHECK ("ENCRYPTED_DATA_KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C007887" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C007888" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C007889" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C007890" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C007891" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C007892" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_BETA" ADD CONSTRAINT "SYS_C007893" CHECK ("ENCRYPTED_DATA_KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CONFIG_INFO_BETA
-- ----------------------------
CREATE UNIQUE INDEX "UK_D_G_T"
  ON "CONFIG_INFO_BETA" ("DATA_ID" ASC, "GROUP_ID" ASC, "TENANT_ID" ASC) LOCAL
  LOGGING
  ONLINE
  NOSORT
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table CONFIG_INFO_TAG
-- ----------------------------
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012435" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CONFIG_INFO_TAG
-- ----------------------------
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012381" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012382" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012383" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012384" CHECK ("TAG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012385" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012386" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C0012387" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C007902" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C007903" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C007904" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C007905" CHECK ("TAG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C007906" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C007907" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_INFO_TAG" ADD CONSTRAINT "SYS_C007908" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CONFIG_INFO_TAG
-- ----------------------------
CREATE UNIQUE INDEX "UK_D_G_T_T"
  ON "CONFIG_INFO_TAG" ("DATA_ID" ASC, "GROUP_ID" ASC, "TENANT_ID" ASC, "TAG_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table CONFIG_TAGS_RELATION
-- ----------------------------
ALTER TABLE "CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0012436" PRIMARY KEY ("NID");

-- ----------------------------
-- Checks structure for table CONFIG_TAGS_RELATION
-- ----------------------------
ALTER TABLE "CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0012388" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0012389" CHECK ("TAG_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0012390" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0012391" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C0012392" CHECK ("NID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C007928" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C007929" CHECK ("TAG_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C007930" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C007931" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CONFIG_TAGS_RELATION" ADD CONSTRAINT "SYS_C007932" CHECK ("NID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CONFIG_TAGS_RELATION
-- ----------------------------
CREATE INDEX "IDX_T"
  ON "CONFIG_TAGS_RELATION" ("TENANT_ID" ASC) LOCAL
  LOGGING
  ONLINE
  NOSORT
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "UK_I_T_T"
  ON "CONFIG_TAGS_RELATION" ("ID" ASC, "TAG_NAME" ASC, "TAG_TYPE" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table GROUP_CAPACITY
-- ----------------------------
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012438" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table GROUP_CAPACITY
-- ----------------------------
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012393" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012394" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012395" CHECK ("QUOTA" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012396" CHECK ("USAGE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012397" CHECK ("MAX_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012398" CHECK ("MAX_AGGR_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012399" CHECK ("MAX_AGGR_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012400" CHECK ("MAX_HISTORY_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012401" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C0012402" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C007939" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C007940" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C007941" CHECK ("QUOTA" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C007942" CHECK ("USAGE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C007943" CHECK ("MAX_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C007944" CHECK ("MAX_AGGR_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C007945" CHECK ("MAX_AGGR_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C007946" CHECK ("MAX_HISTORY_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C007947" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GROUP_CAPACITY" ADD CONSTRAINT "SYS_C007948" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table GROUP_CAPACITY
-- ----------------------------
CREATE UNIQUE INDEX "UK_GR_ID"
  ON "GROUP_CAPACITY" ("GROUP_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table HIS_CONFIG_INFO
-- ----------------------------
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0012439" PRIMARY KEY ("NID");

-- ----------------------------
-- Checks structure for table HIS_CONFIG_INFO
-- ----------------------------
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0012408" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0012409" CHECK ("NID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0012410" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0012411" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0012412" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0012413" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C0012414" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C007960" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C007961" CHECK ("NID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C007962" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C007963" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C007964" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C007965" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "HIS_CONFIG_INFO" ADD CONSTRAINT "SYS_C007966" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table HIS_CONFIG_INFO
-- ----------------------------
CREATE INDEX "IDX_DID"
  ON "HIS_CONFIG_INFO" ("DATA_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "IDX_GMT_CREATE"
  ON "HIS_CONFIG_INFO" ("GMT_CREATE" ASC) LOCAL
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "IDX_GMT_MODIFIED"
  ON "HIS_CONFIG_INFO" ("GMT_MODIFIED" ASC) LOCAL
  LOGGING
  ONLINE
  NOSORT
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Triggers structure for table HIS_CONFIG_INFO
-- ----------------------------
CREATE TRIGGER "TG_DATE" BEFORE INSERT OR UPDATE ON "HIS_CONFIG_INFO" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
     IF INSERTING THEN     
        :NEW.GMT_CREATE := SYSDATE;
        :NEW.GMT_MODIFIED := SYSDATE;
    ELSIF UPDATING then     
        :NEW.GMT_MODIFIED := SYSDATE;
    END IF;    
END;
/
CREATE TRIGGER "TG_HIS_CONFIG" BEFORE INSERT ON "HIS_CONFIG_INFO" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
begin
select /*序列*/SEQ_ID.nextval into:new.nid/*主键*/ from dual;
-- select /*序列*/seq_test.nextval into:new.id/*主键*/ from dual;
end;
/

-- ----------------------------
-- Checks structure for table PERMISSIONS
-- ----------------------------
ALTER TABLE "PERMISSIONS" ADD CONSTRAINT "SYS_C0012403" CHECK ("ROLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PERMISSIONS" ADD CONSTRAINT "SYS_C0012404" CHECK ("RESOURCE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PERMISSIONS" ADD CONSTRAINT "SYS_C0012405" CHECK ("ACTION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PERMISSIONS" ADD CONSTRAINT "SYS_C007975" CHECK ("ROLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PERMISSIONS" ADD CONSTRAINT "SYS_C007976" CHECK ("RESOURCE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PERMISSIONS" ADD CONSTRAINT "SYS_C007977" CHECK ("ACTION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table PERMISSIONS
-- ----------------------------
CREATE UNIQUE INDEX "UK_ROLE_PERMISSION"
  ON "PERMISSIONS" ("ROLE" ASC, "RESOURCE" ASC, "ACTION" ASC) LOCAL
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Checks structure for table ROLES
-- ----------------------------
ALTER TABLE "ROLES" ADD CONSTRAINT "SYS_C0012406" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ROLES" ADD CONSTRAINT "SYS_C0012407" CHECK ("ROLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ROLES" ADD CONSTRAINT "SYS_C007981" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ROLES" ADD CONSTRAINT "SYS_C007982" CHECK ("ROLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table ROLES
-- ----------------------------
CREATE UNIQUE INDEX "IDX_USER_ROLE"
  ON "ROLES" ("USERNAME" ASC, "ROLE" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table TENANT_CAPACITY
-- ----------------------------
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012440" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TENANT_CAPACITY
-- ----------------------------
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012416" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012417" CHECK ("TENANT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012418" CHECK ("QUOTA" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012419" CHECK ("USAGE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012420" CHECK ("MAX_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012421" CHECK ("MAX_AGGR_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012422" CHECK ("MAX_AGGR_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012423" CHECK ("MAX_HISTORY_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012424" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012425" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C007985" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C007986" CHECK ("TENANT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C007987" CHECK ("QUOTA" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C007988" CHECK ("USAGE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C007989" CHECK ("MAX_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C007990" CHECK ("MAX_AGGR_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C007991" CHECK ("MAX_AGGR_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C007992" CHECK ("MAX_HISTORY_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C007993" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_CAPACITY" ADD CONSTRAINT "SYS_C007994" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table TENANT_CAPACITY
-- ----------------------------
CREATE UNIQUE INDEX "UK_T"
  ON "TENANT_CAPACITY" ("TENANT_ID" ASC) LOCAL
  LOGGING
  ONLINE
  NOSORT
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table TENANT_INFO
-- ----------------------------
ALTER TABLE "TENANT_INFO" ADD CONSTRAINT "SYS_C0012441" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TENANT_INFO
-- ----------------------------
ALTER TABLE "TENANT_INFO" ADD CONSTRAINT "SYS_C0012426" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_INFO" ADD CONSTRAINT "SYS_C0012427" CHECK ("KP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_INFO" ADD CONSTRAINT "SYS_C0012428" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_INFO" ADD CONSTRAINT "SYS_C0012429" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_INFO" ADD CONSTRAINT "SYS_C008022" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_INFO" ADD CONSTRAINT "SYS_C008023" CHECK ("KP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_INFO" ADD CONSTRAINT "SYS_C008024" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TENANT_INFO" ADD CONSTRAINT "SYS_C008025" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table TENANT_INFO
-- ----------------------------
CREATE INDEX "IDX_TENANT_ID"
  ON "TENANT_INFO" ("TENANT_ID" ASC) LOCAL
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE UNIQUE INDEX "UK_TENANT_INFO_KPTENANTID"
  ON "TENANT_INFO" ("KP" ASC, "TENANT_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Triggers structure for table TENANT_INFO
-- ----------------------------
CREATE TRIGGER "TG_TENANT_INFO" BEFORE INSERT ON "TENANT_INFO" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
begin
select /*序列*/SEQ_ID.nextval into:new.ID/*主键*/ from dual;
-- select /*序列*/seq_test.nextval into:new.id/*主键*/ from dual;
end;
/

-- ----------------------------
-- Primary Key structure for table USERS
-- ----------------------------
ALTER TABLE "USERS" ADD CONSTRAINT "SYS_C0012442" PRIMARY KEY ("USERNAME");

-- ----------------------------
-- Checks structure for table USERS
-- ----------------------------
ALTER TABLE "USERS" ADD CONSTRAINT "SYS_C0012430" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "USERS" ADD CONSTRAINT "SYS_C0012431" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "USERS" ADD CONSTRAINT "SYS_C0012432" CHECK ("ENABLED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "USERS" ADD CONSTRAINT "SYS_C008015" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "USERS" ADD CONSTRAINT "SYS_C008016" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "USERS" ADD CONSTRAINT "SYS_C008017" CHECK ("ENABLED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
