
-- ----------------------------
-- Table structure for PERMISSIONS
-- ----------------------------
CREATE TABLE "SYSTEM"."PERMISSIONS" (
  "ROLE" NVARCHAR2(50) NOT NULL,
  "RESOURCE" NVARCHAR2(255) NOT NULL,
  "ACTION" NVARCHAR2(8) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PERMISSIONS
-- ----------------------------
INSERT INTO "SYSTEM"."PERMISSIONS" ("ROLE", "RESOURCE", "ACTION") VALUES ('user', ':*:*', 'rw');
COMMIT;
COMMIT;

-- ----------------------------
-- Checks structure for table PERMISSIONS
-- ----------------------------
ALTER TABLE "SYSTEM"."PERMISSIONS" ADD CONSTRAINT "SYS_C0012403" CHECK ("ROLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."PERMISSIONS" ADD CONSTRAINT "SYS_C0012404" CHECK ("RESOURCE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."PERMISSIONS" ADD CONSTRAINT "SYS_C0012405" CHECK ("ACTION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table PERMISSIONS
-- ----------------------------
CREATE UNIQUE INDEX "SYSTEM"."UK_ROLE_PERMISSION"
  ON "SYSTEM"."PERMISSIONS" ("ROLE" ASC, "RESOURCE" ASC, "ACTION" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
);
