
-- ----------------------------
-- Table structure for TENANT_CAPACITY
-- ----------------------------
CREATE TABLE "SYSTEM"."TENANT_CAPACITY" (
  "ID" NUMBER(20,0) NOT NULL,
  "TENANT_ID" NVARCHAR2(128) NOT NULL,
  "QUOTA" NUMBER(11,0) NOT NULL,
  "USAGE" NUMBER(11,0) NOT NULL,
  "MAX_SIZE" NUMBER(11,0) NOT NULL,
  "MAX_AGGR_COUNT" NUMBER(11,0) NOT NULL,
  "MAX_AGGR_SIZE" NUMBER(11,0) NOT NULL,
  "MAX_HISTORY_COUNT" NUMBER(11,0) NOT NULL,
  "GMT_CREATE" DATE NOT NULL,
  "GMT_MODIFIED" DATE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SYSTEM"."TENANT_CAPACITY"."ID" IS '主键ID';
COMMENT ON COLUMN "SYSTEM"."TENANT_CAPACITY"."TENANT_ID" IS 'Tenant ID';
COMMENT ON COLUMN "SYSTEM"."TENANT_CAPACITY"."QUOTA" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "SYSTEM"."TENANT_CAPACITY"."USAGE" IS '使用量';
COMMENT ON COLUMN "SYSTEM"."TENANT_CAPACITY"."MAX_SIZE" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "SYSTEM"."TENANT_CAPACITY"."MAX_AGGR_COUNT" IS '聚合子配置最大个数';
COMMENT ON COLUMN "SYSTEM"."TENANT_CAPACITY"."MAX_AGGR_SIZE" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "SYSTEM"."TENANT_CAPACITY"."MAX_HISTORY_COUNT" IS '最大变更历史数量';
COMMENT ON COLUMN "SYSTEM"."TENANT_CAPACITY"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "SYSTEM"."TENANT_CAPACITY"."GMT_MODIFIED" IS '修改时间';
COMMENT ON TABLE "SYSTEM"."TENANT_CAPACITY" IS '租户容量信息表';

-- ----------------------------
-- Records of TENANT_CAPACITY
-- ----------------------------
COMMIT;
COMMIT;

-- ----------------------------
-- Primary Key structure for table TENANT_CAPACITY
-- ----------------------------
ALTER TABLE "SYSTEM"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012440" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TENANT_CAPACITY
-- ----------------------------
ALTER TABLE "SYSTEM"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012416" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012417" CHECK ("TENANT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012418" CHECK ("QUOTA" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012419" CHECK ("USAGE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012420" CHECK ("MAX_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012421" CHECK ("MAX_AGGR_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012422" CHECK ("MAX_AGGR_SIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012423" CHECK ("MAX_HISTORY_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012424" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."TENANT_CAPACITY" ADD CONSTRAINT "SYS_C0012425" CHECK ("GMT_MODIFIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table TENANT_CAPACITY
-- ----------------------------
CREATE UNIQUE INDEX "SYSTEM"."UK_T"
  ON "SYSTEM"."TENANT_CAPACITY" ("TENANT_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
);
