
-- ----------------------------
-- Table structure for USERS
-- ----------------------------
CREATE TABLE "SYSTEM"."USERS" (
  "USERNAME" NVARCHAR2(50) NOT NULL,
  "PASSWORD" NVARCHAR2(500) NOT NULL,
  "ENABLED" NUMBER(4,0) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of USERS
-- ----------------------------
INSERT INTO "SYSTEM"."USERS" ("USERNAME", "PASSWORD", "ENABLED") VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', '1');
INSERT INTO "SYSTEM"."USERS" ("USERNAME", "PASSWORD", "ENABLED") VALUES ('fxz', '$2a$10$kgxkmVzxCrvy43WNQ57Gk.b5eaJ9SwGZ1DxXUeWAlGjh3Htvi/nGC', '1');
COMMIT;
COMMIT;

-- ----------------------------
-- Primary Key structure for table USERS
-- ----------------------------
ALTER TABLE "SYSTEM"."USERS" ADD CONSTRAINT "SYS_C0012442" PRIMARY KEY ("USERNAME");

-- ----------------------------
-- Checks structure for table USERS
-- ----------------------------
ALTER TABLE "SYSTEM"."USERS" ADD CONSTRAINT "SYS_C0012430" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."USERS" ADD CONSTRAINT "SYS_C0012431" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEM"."USERS" ADD CONSTRAINT "SYS_C0012432" CHECK ("ENABLED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
